public enum ESkills
{
    None,
    BasicAttack,
    MoveForwards,
    MoveBackwards,
    HitTwice,
    Knockback,
    DamageOverTime,
    BuffEvasion,
    Execute,
    Fireball,
    Lightning,
    AirBlast,
    StrongHit,
    Heal,
    HealOverTime,
    EarthStrike,
    BuffDamage,
    BuffArmor
}